name: Docs

permissions:
  contents: write

on:
  - workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.GH_TOKEN }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Setup Git
        run: |
          git config user.name "GitHub Bot"
          git config user.email "gituser@example.com"

      - name: NPM Install
        run: npm ci

      - name: Build Main Website
        shell: bash
        run: npx nx run spaceribs:build:production

      - name: Build Static Website
        shell: bash
        run: npm run scully

      - name: Build Typedoc
        shell: bash
        run: npx nx run-many --target=typedoc

      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
